# Generated by Django 4.2.11 on 2024-03-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField()),
                ('official_homepage', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
