# Generated by Django 4.2.9 on 2024-03-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
